plugins:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

