language: ruby
cache: bundler
before_install:
  - gem install bundler # use the latest bundler, since Travis doesn't update for us
rvm:
  - 2.6.0
  - 2.5.0
script:
  - bundle exec rspec
  - bundle exec rubocop
