pipeline:
  build:
    image: ruby:3.3
    commands:
      - apt-get update -qq
      - apt-get install -y build-essential
      - mkdir -p $HOME/.gem
      - touch $HOME/.gem/credentials
      - chmod 0600 $HOME/.gem/credentials
      - printf -- "---\n:rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}" > $HOME/.gem/credentials
      - gem build *.gemspec
      - gem push *.gem
    secrets: [ rubygems_auth_token ]
    when:
      event: tag