name: 💎 Ruby

on: push

permissions:
  contents: read
  
jobs:
  test:
    name: 🧪 Test (ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache gems
    - name: Run tests
      run: bundle exec rspec --format progress

    - name: Report coverage
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/coverage.xml

  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true # 'bundle install' and cache gems
    - name: Lint
      run: make lint
